name: image-viewer

on: [push]

jobs:
  build:

    # using Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm install -g @angular/cli
    - run: ng build image-viewer --prod
